language: java
sudo: false

jdk:
  - openjdk8
  
env:
  - DISPLAY=:99.0

services:
  - xvfb

install: true

script:
  - mvn package -Dgpg.skip=true

before_cache:
  - rm -fr $HOME/.m2/repository/net/mikehardy/google-analytics-java7

cache:
  directories:
    - $HOME/.m2
